# This is a generated file. Not intended for manual editing.
services:
  devhabit.api:
    build:
      context: "/Users/luis/Documents/Projects/DevHabit"
      dockerfile: "src/DevHabit.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/DevHabit.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "devhabit.api:dev"
    ports: []
    volumes:
    - "/Users/luis/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/luis/Documents/Projects/DevHabit/src/DevHabit.Api:/app:rw"
    - "/Users/luis/Documents/Projects/DevHabit:/src:rw"
    working_dir: "/app"
